### ISSUE TITLE
Item inside Stationary Potato Cannon get removed when pushed by mechanical piston or mechanical sticky piston

### ISSUE THREAD

**Issue by furuochen-dev** [Ruochenfu2011/CreateMorePotatoes#11]
Issue found by NiceCPU#8721

**Comment by JieningYu** [comment]
Just simply make it non-pushable as block entities can't be pushed by vanilla pistons in Java Edition.

**Comment by furuochen-dev** [comment]
@JieningYu it is not pushable by vanilla piston since it's a block entity, I actually meant mechanical pistons

**Comment by furuochen-dev** [comment]
title edited

**Comment by JieningYu** [comment]
You didn't read&write nbt with the block entity.

**Comment by JieningYu** [comment]
I suggest to make it an inventory

**Comment by furuochen-dev** [comment]
> You didn't read&write nbt with the block entity.

i know, will be in 1.1

**Comment by furuochen-dev** [comment]
i found out after making this issue, and i forgot to fix in 1.0 /shrug

**Comment by furuochen-dev** [comment]
fabric fixed #14

**Comment by furuochen-dev** [comment]
forge fixed #15 (v1.0.2)
