### ISSUE TITLE
Server crash on startup 1.18.2

### ISSUE THREAD

**Issue by F0xtastic** [Ruochenfu2011/CreateMorePotatoes#18]
The server crashed referencing this mod and claims it tried to load client-side features. This is specifically with only Create, Flywheel, and CreateMorePotatoes installed. 

https://mclo.gs/m9CDbi9

I don't anticipate this is a client-side mod but I could be wrong! Thanks for your time either way. ^^

**Comment by furuochen-dev** [comment]
looking in to it now!

**Comment by furuochen-dev** [comment]
forge should be fixed in a80228a

**Comment by furuochen-dev** [comment]
@JieningYu

**Comment by furuochen-dev** [comment]
though is fabric fixed

**Comment by JieningYu** [comment]
> though is fabric fixed

Fabric don't need to fix this

**Comment by furuochen-dev** [comment]
ok

**Comment by furuochen-dev** [comment]
probably fixed in 1.2

**Comment by furuochen-dev** [comment]
Quick Issue preview: Colour handler should not be executed on server

**Comment by JieningYu** [comment]
Why don't just put it in `clientSetup`?

**Comment by furuochen-dev** [comment]
I don't know, but this is anyway resolved
