### ISSUE TITLE
Won't work on servers...

### ISSUE THREAD

**Issue by TheTennessee** [Ruochenfu2011/CreateMorePotatoes#23]
So, I'm just going to let you know rather than making a full bug report. Your EffectHandler mixin is only set to work on the client, so it doesn't work on a server, at all.

I honestly spent a huge amount of time trying to figure out what the issue was on my end, and finally saw this in the mixin.json.

**Comment by furuochen-dev** [comment]
Fix when have time

**Comment by TheTennessee** [comment]
It is literally change your createmorepotatoes.mixins.json to:

`{
  "required": true,
  "package": "net.forsteri.createmorepotatoes.mixin",
  "compatibilityLevel": "JAVA_17",
  "mixins": [
    "EffectHandler"
  ],
  "client": [
  ],
  "minVersion": "0.8"
}`

**Comment by furuochen-dev** [comment]
Takes time to publish to curseforge

**Comment by furuochen-dev** [comment]
Actually I don't want to maintain anymore
